version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          memory: 6G
    volumes:
      - ./ollama:/root/.ollama   # Persistência dos modelos
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
    - "6333:6333" # REST
    - "6334:6334" # gRPC
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped
